# Generated by Django 6.0.5 on 2026-05-17 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads_gallery/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Фотография объявления',
                'verbose_name_plural': 'Фотографии объявлений',
            },
        ),
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
        migrations.CreateModel(
            name='AdImageLine',
            fields=[
                ('adimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.adimage')),
            ],
            bases=('ads.adimage',),
        ),
        migrations.AddField(
            model_name='adimage',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ad', verbose_name='Обявление'),
        ),
    ]
