# Generated by Django 6.0.5 on 2026-05-17 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_adimage_remove_ad_image_adimageline_adimage_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.ad', verbose_name='Обявление'),
        ),
        migrations.DeleteModel(
            name='AdImageLine',
        ),
    ]
